INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1000);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1002);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1022);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1025);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1033);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1035);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1035);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1039);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1041);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1044);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1045);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1045);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1047);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1050);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1051);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1055);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1059);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1066);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1070);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1074);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1077);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1270);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1370);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1470);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1570);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1670);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1803);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1870);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('payday!','HAPPY',1970);

INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',1970);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2000);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2100);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2200);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2300);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2400);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2500);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2600);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2700);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Coffee tastes bad','UNHAPPY',2700);

INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1059);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1066);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1070);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1074);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1077);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1270);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1370);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1370);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Fedex Rocks!','HAPPY',1370);


INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1077);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1087);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1107);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1127);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1277);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1377);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1477);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1487);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1497);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1500);

INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1077);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1097);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1177);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1277);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1357);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1387);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1477);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1577);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1677);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1777);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1777);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1777);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1777);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','HAPPY',1777);

INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','UNHAPPY',1377);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','UNHAPPY',1477);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','UNHAPPY',1577);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','UNHAPPY',1677);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','UNHAPPY',1777);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','UNHAPPY',1787);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','UNHAPPY',1797);
INSERT INTO VoteEntity(TAG, MOOD, TIME) values ('Comfortable charis','NEUTRAL',1997);
